import React, { useState } from 'react';
import { outLicensingDeals, outLicensingSummary } from '../data/mockData';
import { 
  Briefcase, Activity, TrendingUp, DollarSign, Search, 
  MapPin, Globe, Lock, CheckCircle2, FlaskConical, Target, Building2, ChevronRight, BarChart3, PieChart, Star
} from 'lucide-react';
import Button from './ui/Button';

export default function DealTracker({ userRole, setView }) {
  const [searchTerm, setSearchTerm] = useState('');
  const [targetArea, setTargetArea] = useState('All');
  const [expandedRow, setExpandedRow] = useState(null);

  const areas = ['All', 'Oncology', 'Autoimmune', 'Metabolic', 'Neurology / Autoimmune', 'Cardiovascular'];

  const filteredDeals = outLicensingDeals.filter(deal => {
    const matchSearch = deal.licensor.toLowerCase().includes(searchTerm.toLowerCase()) || 
                        deal.licensee.toLowerCase().includes(searchTerm.toLowerCase()) ||
                        deal.drug.toLowerCase().includes(searchTerm.toLowerCase());
    const matchArea = targetArea === 'All' || deal.therapeuticArea.includes(targetArea);
    return matchSearch && matchArea;
  });

  const chartData = {
    'Oncology': 10,
    'Autoimmune': 2,
    'Metabolic': 2,
    'Cardiovascular': 1
  };

  return (
    <div className="space-y-8 animate-in mt-6">
      <div className="flex flex-col md:flex-row items-center justify-between mb-8 gap-4">
        <div>
          <h1 className="text-2xl font-black text-white uppercase tracking-widest flex items-center gap-3">
            <Globe className="text-cyan-500" size={28} />
            China Out-Licensing Tracker
          </h1>
          <p className="text-sm text-slate-400 mt-2 max-w-2xl">
            Real-time feed of cross-border BD deals. Explore $52B+ generated by Chinese biotech out-licensing to Western multinationals in 2025-2026.
          </p>
        </div>
        <div className="bg-slate-900 border border-slate-700 p-3 rounded-xl flex items-center gap-4 shrink-0 shadow-lg shadow-cyan-500/10">
           <div className="text-right">
             <div className="text-[10px] text-slate-400 font-bold uppercase tracking-widest mb-1">Time Period</div>
             <div className="text-sm text-cyan-400 font-black">{outLicensingSummary.timePeriod}</div>
           </div>
        </div>
      </div>

      {/* Hero Stats */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {[
          { label: 'Total Q1 Tracked Value', value: outLicensingSummary.totalValue, icon: DollarSign, color: 'text-indigo-400', bg: 'bg-indigo-500/10' },
          { label: 'Deal Count', value: outLicensingSummary.dealCount, icon: Briefcase, color: 'text-cyan-400', bg: 'bg-cyan-500/10' },
          { label: 'Avg Deal Size', value: outLicensingSummary.avgDealSize, icon: Activity, color: 'text-emerald-400', bg: 'bg-emerald-500/10' },
          { label: 'YoY Growth', value: outLicensingSummary.yoyGrowth, icon: TrendingUp, color: 'text-amber-400', bg: 'bg-amber-500/10' },
        ].map((stat, i) => (
          <div key={i} className="bg-slate-900 border border-slate-800 p-5 rounded-2xl flex items-start gap-4 hover:border-slate-700 transition-colors">
            <div className={`p-3 rounded-xl ${stat.bg}`}>
              <stat.icon size={20} className={stat.color} />
            </div>
            <div>
              <div className="text-[10px] font-bold text-slate-500 uppercase tracking-widest mb-1">{stat.label}</div>
              <div className={`text-2xl font-black font-mono tracking-tight ${stat.color}`}>{stat.value}</div>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Deal Table Area */}
        <div className="lg:col-span-8 bg-slate-900 border border-slate-800 rounded-2xl overflow-hidden flex flex-col">
          <div className="p-5 border-b border-slate-800 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 bg-slate-800/20">
            <div className="flex items-center gap-2 overflow-x-auto hide-scrollbar w-full sm:w-auto">
              {areas.map(a => (
                <button
                  key={a}
                  onClick={() => setTargetArea(a)}
                  className={`px-3 py-1.5 rounded-lg text-[10px] font-black uppercase tracking-widest whitespace-nowrap transition-all border ${targetArea === a ? 'bg-cyan-500/20 text-cyan-400 border-cyan-500/50' : 'bg-slate-950 text-slate-400 border-slate-800 hover:border-slate-600'}`}
                >
                  {a}
                </button>
              ))}
            </div>
            <div className="relative w-full sm:w-auto">
              <input
                type="text"
                placeholder="Search deals..."
                className="bg-slate-950 border border-slate-800 rounded-lg pl-9 pr-4 py-2 text-xs text-white placeholder-slate-500 w-full sm:w-64 focus:outline-none focus:border-cyan-500 transition-colors"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
              />
              <Search className="w-4 h-4 text-slate-500 absolute left-3 top-1/2 -translate-y-1/2" />
            </div>
          </div>

          <div className="overflow-x-auto flex-1 custom-scrollbar">
            <table className="w-full text-left border-collapse min-w-[800px]">
              <thead className="bg-slate-950/50">
                <tr className="border-b border-slate-800">
                  <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Date</th>
                  <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Deal Pair</th>
                  <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Asset / Target</th>
                  <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest text-right">Value (Upfront)</th>
                  <th className="py-3 px-4 text-[10px] font-black text-slate-500 uppercase tracking-widest">Stage</th>
                </tr>
              </thead>
              <tbody>
                {filteredDeals.length > 0 ? filteredDeals.map((deal) => (
                  <React.Fragment key={deal.id}>
                    <tr 
                      className={`border-b border-slate-800/50 hover:bg-slate-800/30 cursor-pointer transition-colors ${expandedRow === deal.id ? 'bg-slate-800/30' : ''}`}
                      onClick={() => setExpandedRow(expandedRow === deal.id ? null : deal.id)}
                    >
                      <td className="py-4 px-4 text-[11px] font-mono text-slate-400">{deal.date}</td>
                      <td className="py-4 px-4">
                        <div className="flex flex-col">
                          <span className="font-bold text-slate-200 text-sm">{deal.licensor}</span>
                          <span className="text-[10px] font-bold text-indigo-400 flex items-center gap-1">
                            <ArrowRightIcon className="w-3 h-3" /> {deal.licensee}
                          </span>
                        </div>
                      </td>
                      <td className="py-4 px-4">
                        <div className="flex flex-col">
                          <span className="font-bold text-white text-xs">{deal.drug}</span>
                          <span className="text-[10px] text-slate-500 bg-slate-800 inline-block px-1.5 py-0.5 rounded mt-0.5 w-max">
                            {deal.target}
                          </span>
                        </div>
                      </td>
                      <td className="py-4 px-4 text-right">
                        <div className="flex flex-col items-end">
                          <span className="font-mono font-black text-emerald-400 text-sm">{deal.value}</span>
                          <span className="font-mono text-[10px] text-slate-500">({deal.upfront})</span>
                        </div>
                      </td>
                      <td className="py-4 px-4">
                        <div className="flex flex-col">
                          <span className="text-xs text-slate-300 font-medium">{deal.stage}</span>
                          <span className="text-[10px] text-slate-500">{deal.modality}</span>
                        </div>
                      </td>
                    </tr>
                    {expandedRow === deal.id && (
                      <tr className="bg-slate-900/80 border-b border-slate-800">
                        <td colSpan={5} className="p-0">
                          <div className="p-4 border-l-2 border-cyan-500 flex items-start gap-4">
                            <div className="p-2 bg-slate-800 rounded-lg shrink-0">
                              <FlaskConical className="w-5 h-5 text-cyan-400" />
                            </div>
                            <div className="flex-1">
                              <h4 className="text-[10px] font-black uppercase text-slate-500 tracking-widest mb-1">Strategic Context & BioQuantix Intelligence</h4>
                              {userRole === 'visitor' ? (
                                <div className="blur-sm select-none pointer-events-none text-xs text-slate-400 leading-relaxed italic max-w-2xl">
                                  This is a highly valuable asset due to its dual mechanism of action. The licensee is heavily focused on expanding into this indication to defend against upcoming patent cliffs in the late 2020s. Proprietary data suggests pricing power is extremely favorable.
                                </div>
                              ) : (
                                <div className="text-xs text-slate-300 leading-relaxed max-w-3xl">
                                  {deal.notes}
                                </div>
                              )}
                              {userRole === 'visitor' && (
                                <div className="mt-3">
                                  <Button variant="outline" size="sm" onClick={() => setView('auth')} className="text-[9px] py-1.5! border-cyan-500/30 text-cyan-400 hover:bg-cyan-500/10">
                                    <Lock size={10} className="mr-1 inline-block" /> Sign in to view full intelligence notes
                                  </Button>
                                </div>
                              )}
                            </div>
                            <div className="shrink-0 text-right pr-4 hidden md:block">
                               <div className="text-[9px] font-black text-slate-500 uppercase tracking-widest mb-1">Deal Structure</div>
                               <div className="text-xs text-blue-400 font-bold">{deal.structure}</div>
                            </div>
                          </div>
                        </td>
                      </tr>
                    )}
                  </React.Fragment>
                )) : (
                  <tr>
                    <td colSpan={5} className="py-12 text-center text-slate-500 text-sm">
                      No deals found matching the criteria.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        {/* Sidebar */}
        <div className="lg:col-span-4 space-y-6 flex flex-col">
          {/* Spotlight Card */}
          <div className="bg-gradient-to-br from-indigo-900/40 to-slate-900 border border-indigo-500/30 rounded-2xl p-6 relative overflow-hidden shadow-2xl shadow-indigo-500/5">
            <div className="absolute -top-6 -right-6 w-32 h-32 bg-indigo-500/10 blur-2xl rounded-full pointer-events-none" />
            
            <div className="inline-flex items-center gap-1.5 bg-indigo-500/20 border border-indigo-500/40 text-indigo-300 text-[9px] font-black px-2 py-0.5 rounded-full mb-5 uppercase tracking-widest">
              <Star size={10} className="fill-indigo-400" /> Spotlight Deal
            </div>
            
            <h3 className="text-xl font-black text-white leading-tight mb-2">Sino Biopharma × Sanofi</h3>
            <p className="text-[11px] font-mono text-emerald-400 font-black mb-4">$1.53B Total • $135M Upfront</p>
            
            <div className="space-y-4 mb-6 relative z-10">
              <div className="bg-slate-950/60 rounded-xl p-3 border border-slate-800">
                <div className="text-[9px] font-bold text-slate-500 uppercase tracking-widest mb-1">Asset</div>
                <div className="text-sm font-bold text-slate-200">rovadicitinib (Anxu)</div>
                <div className="text-[10px] text-indigo-400 font-medium">JAK / ROCK Dual Inhibitor</div>
              </div>

              <div className="bg-slate-950/60 rounded-xl p-3 border border-slate-800 relative group">
                <div className="text-[9px] font-bold text-slate-500 uppercase tracking-widest flex justify-between items-center mb-1">
                  <span>BioQuantix Analysis</span>
                </div>
                {userRole === 'visitor' ? (
                  <div className="flex flex-col items-center justify-center p-2 mt-1">
                     <Lock className="text-indigo-500/50 mb-2" size={16} />
                     <p className="text-[10px] text-slate-500 text-center italic leading-relaxed blur-[2px] select-none">
                       Rovadicitinib requires strong NRDL positioning in China to maximize cash flow while Phase 3 U.S. cGVHD trials proceed.
                     </p>
                  </div>
                ) : (
                  <p className="text-xs text-slate-300 leading-relaxed italic">
                    "This $1.53B deal requires meticulous competitive intelligence. Rovadicitinib needs strict NRDL positioning in China AND a global pricing strategy for optimal ROI."
                  </p>
                )}
              </div>
            </div>

            <Button 
               variant={userRole === 'visitor' ? "primary" : "outline"}
               className={userRole === 'visitor' ? "w-full text-xs shadow-indigo-500/20" : "w-full text-xs border-indigo-500/30 text-indigo-300 hover:bg-indigo-500/10"}
               onClick={() => userRole === 'visitor' ? setView('auth') : setView('dashboard')}
            >
              {userRole === 'visitor' ? 'UNLOCK PRICING INTEL' : 'VIEW MARKET MAP'}
            </Button>
          </div>

          {/* Trend Chart */}
          <div className="bg-slate-900 border border-slate-800 rounded-2xl p-5 flex-1 flex flex-col">
            <h3 className="text-xs font-black uppercase text-slate-400 tracking-widest flex items-center gap-2 mb-6">
              <PieChart size={14} className="text-cyan-500" /> TA Deal Volume (Q1 '26)
            </h3>
            
            <div className="space-y-4 flex-1">
              {[
                { name: 'Oncology', count: 10, color: 'bg-red-500', width: '100%' },
                { name: 'Immunology', count: 3, color: 'bg-indigo-500', width: '30%' },
                { name: 'Metabolic', count: 2, color: 'bg-emerald-500', width: '20%' },
                { name: 'Cardiovascular', count: 1, color: 'bg-blue-500', width: '10%' },
              ].map(ta => (
                <div key={ta.name} className="space-y-1.5">
                  <div className="flex justify-between items-end">
                    <span className="text-[10px] font-black text-slate-300 uppercase tracking-widest">{ta.name}</span>
                    <span className="text-[10px] font-mono text-slate-500">{ta.count} DEALS</span>
                  </div>
                  <div className="h-1.5 w-full bg-slate-800 rounded-full overflow-hidden">
                    <div className={`h-full ${ta.color}`} style={{ width: ta.width }} />
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-6 p-4 bg-slate-800/20 border border-slate-800 rounded-xl">
               <p className="text-[10px] text-slate-500 leading-relaxed italic text-center">
                 Oncology continues to dominate the licensing landscape, specifically with next-generation ADCs and bispecifics.
               </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

// Inline Icon Component for ArrowRight to avoid imports
function ArrowRightIcon(props) {
  return (
    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      width="24" height="24" viewBox="0 0 24 24" fill="none" 
      stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" 
      {...props}
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  );
}
